/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 24 19:08:22 GMT 2023
 */

package com.example.Amit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Amit.model.Company;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Company company0 = new Company();
  }
}
