/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 24 19:06:38 GMT 2023
 */

package com.example.Amit.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Amit.exception.SectorNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SectorNotFoundException_ESTest extends SectorNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException("] to org.eclipse.jetty.server.Request");
      String string0 = sectorNotFoundException0.getMessage();
      assertEquals("] to org.eclipse.jetty.server.Request", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException("");
      String string0 = sectorNotFoundException0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      boolean boolean0 = sectorNotFoundException0.canEqual(sectorNotFoundException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      Object object0 = new Object();
      boolean boolean0 = sectorNotFoundException0.canEqual(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      String string0 = sectorNotFoundException0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      sectorNotFoundException0.setMessage("SectorNotFoundException(message=null)");
      SectorNotFoundException sectorNotFoundException1 = new SectorNotFoundException();
      boolean boolean0 = sectorNotFoundException0.equals(sectorNotFoundException1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      SectorNotFoundException sectorNotFoundException1 = new SectorNotFoundException();
      boolean boolean0 = sectorNotFoundException0.equals(sectorNotFoundException1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      boolean boolean0 = sectorNotFoundException0.equals("SectorNotFoundException(message=null)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      boolean boolean0 = sectorNotFoundException0.equals(sectorNotFoundException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      sectorNotFoundException0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      sectorNotFoundException0.setMessage("");
      sectorNotFoundException0.hashCode();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      String string0 = sectorNotFoundException0.toString();
      assertEquals("SectorNotFoundException(message=null)", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      sectorNotFoundException0.setMessage("tT[Nd5(O");
      SectorNotFoundException sectorNotFoundException1 = new SectorNotFoundException("tT[Nd5(O");
      boolean boolean0 = sectorNotFoundException0.equals(sectorNotFoundException1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SectorNotFoundException sectorNotFoundException0 = new SectorNotFoundException();
      SectorNotFoundException sectorNotFoundException1 = new SectorNotFoundException("");
      boolean boolean0 = sectorNotFoundException0.equals(sectorNotFoundException1);
      assertFalse(boolean0);
      assertFalse(sectorNotFoundException1.equals((Object)sectorNotFoundException0));
  }
}
