/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 24 19:09:38 GMT 2023
 */

package com.example.Amit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Amit.model.Sector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Sector_ESTest extends Sector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Sector sector0 = new Sector("com.example.Amit.model.Sector", "k+7V", "!O't4L");
      assertEquals("k+7V", sector0.getName());
      
      sector0.setName((String) null);
      sector0.getName();
      assertEquals("com.example.Amit.model.Sector", sector0.getId());
      assertEquals("!O't4L", sector0.getDescription());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Sector sector0 = new Sector((String) null, (String) null, "s0.=RrW;@");
      sector0.setName("v/AX");
      String string0 = sector0.getName();
      assertEquals("v/AX", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Sector sector0 = new Sector("WkXTj2ZVJcSz)PL0!", "WkXTj2ZVJcSz)PL0!", "]E@U/u>r/lFCi-.*g");
      assertEquals("WkXTj2ZVJcSz)PL0!", sector0.getId());
      
      sector0.setId((String) null);
      sector0.getId();
      assertEquals("]E@U/u>r/lFCi-.*g", sector0.getDescription());
      assertEquals("WkXTj2ZVJcSz)PL0!", sector0.getName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Sector sector0 = new Sector("com.example.Amit.model.Sector", "k+7V", "!O't4L");
      assertEquals("com.example.Amit.model.Sector", sector0.getId());
      
      sector0.setId("");
      sector0.getId();
      assertEquals("!O't4L", sector0.getDescription());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Sector sector0 = new Sector((String) null, (String) null, "s0.=RrW;@");
      sector0.setDescription((String) null);
      String string0 = sector0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Sector sector0 = new Sector("com.example.Amit.model.Sector", "k+7V", "!O't4L");
      String string0 = sector0.getDescription();
      assertEquals("!O't4L", string0);
      assertEquals("k+7V", sector0.getName());
      assertEquals("com.example.Amit.model.Sector", sector0.getId());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Sector sector0 = new Sector("com.example.Amit.model.Sector", "k+7V", "!O't4L");
      String string0 = sector0.getId();
      assertEquals("!O't4L", sector0.getDescription());
      assertEquals("com.example.Amit.model.Sector", string0);
      assertEquals("k+7V", sector0.getName());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Sector sector0 = new Sector("", "", "");
      String string0 = sector0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Sector sector0 = new Sector("", "", "");
      String string0 = sector0.getDescription();
      assertEquals("", string0);
  }
}
