/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 24 19:09:22 GMT 2023
 */

package com.example.Amit.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.Amit.model.Sector;
import com.example.Amit.service.SectorServiceImpl;
import java.util.List;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SectorServiceImpl_ESTest extends SectorServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      Sector sector0 = sectorServiceImpl0.save((Sector) null);
      assertNull(sector0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      SectorServiceImpl.l = null;
      List<Sector> list0 = sectorServiceImpl0.findAll();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      SectorServiceImpl.l = null;
      Sector sector0 = mock(Sector.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        sectorServiceImpl0.save(sector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Amit.service.SectorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      SectorServiceImpl.l = null;
      // Undeclared exception!
      try { 
        sectorServiceImpl0.findById("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Amit.service.SectorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      SectorServiceImpl.l = null;
      // Undeclared exception!
      try { 
        sectorServiceImpl0.deleteById("Wsfu)!JMxP>mLZVe");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Amit.service.SectorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      Optional<Sector> optional0 = sectorServiceImpl0.findById("iwc6u?`.|v7VU,nz");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      List<Sector> list0 = sectorServiceImpl0.findAll();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SectorServiceImpl sectorServiceImpl0 = new SectorServiceImpl();
      sectorServiceImpl0.deleteById("Wsfu)!JMxP>mLZVe");
  }
}
